services:
  - type: web
    name: plant-disease-detection
    runtime: python

    rootDir: backend

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app

    plan: free

    autoDeploy: true